routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/news', 'NewsController@index')->name('news');
Route::get('/team', 'TeamController@index')->name('team');
Route::get('/schedule', 'ScheduleController@index')->name('schedule');
Route::get('/groups', 'GroupsController@index')->name('groups');



//Route::namespace('Backend')->prefix('backend')->group(function () {
Route::group(['namespace' => 'Backend', 'prefix' => 'backend'], function () {

    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');

    Route::group(['middleware' => 'auth' ], function() {


        Route::resource('group-age', 'GroupAgeController');
        Route::resource('groups', 'GroupsController');

        Route::get('/schedule/{id}', ['as' => 'group.schedule.create', 'uses' => 'ScheduleController@create']);
        Route::post('/schedule/{id}', ['as' => 'group.schedule.store', 'uses' => 'ScheduleController@store']);

        Route::resource('teachers', 'TeachersController');
        Route::resource('subjects', 'SubjectsController');
        Route::resource('subjects.modules', 'ModulesController');

        Route::get('register-child', ['as' => 'register-child.create', 'uses' => 'RegisterChildController@create']);
        Route::post('register-child', ['as' => 'register-child.store', 'uses' => 'RegisterChildController@store']);
        Route::resource('parents', 'ParentsController');
    });

});

app/Http/Controllers/Backend/GroupAgeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\GroupAge;
use Illuminate\Http\Request;

class GroupAgeController extends Controller
{
    public function index()
    {
        $groupAges = GroupAge::all();
        return view('backend.group-age.index', ['groupAge' => new GroupAge, 'groupAges' => $groupAges ]);

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'from'  => 'required|integer',
            'to'  => 'required|integer',
        ]);

        $groupAge = GroupAge::create($request->only(['title', 'from', 'to']));
        flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е създадена');
        return redirect()->back();
    }

    public function edit($id)
    {
        $groupAge = GroupAge::findOrFail($id);
        return view('backend.group-age.edit', ['groupAge' => $groupAge]);
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'from'  => 'required|integer',
            'to'  => 'required|integer',
        ]);

        /** @var GroupAge $groupAge */
        $groupAge = GroupAge::findOrFail($id);
        $groupAge->update($request->only(['title', 'from', 'to']));

        flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е редактирана');
        return redirect()->route('group-age.index');

    }

    public function destroy($id)
    {
        /** @var GroupAge $groupAge */
        $groupAge = GroupAge::withCount('groups')->findOrFail($id);

        if ($groupAge->groups_count != 0) {
            flash()->error('Възникна грешка', 'Възрастовата група '.$groupAge->title.' не може да бъде изтрита');
        } else {
            $groupAge->delete();
            flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е изтрита');
        }

        return redirect()->route('group-age.index');
    }
}

app/Http/Controllers/Backend/GroupsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Group;
use App\Models\GroupAge;
use App\Models\Teacher;
use Illuminate\Http\Request;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $groups = Group::with('groupAge', 'teachers')->get();
        return view('backend.group.index', [
                'groupAges' => GroupAge::pluck('title', 'id'),
                'group' => new Group,
                'groups' => $groups,
                'teachers' => Teacher::pluck('name', 'id')
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'teachers' => 'required',
            'group_age_id' => 'exists:group_ages,id'
        ]);


        /** @var Group $group */
        $group = Group::create($request->only(['title', 'group_age_id', 'description']));

        $group->teachers()->sync($request->get('teachers'));

        flash()->success('Успех', 'Детска група '.$group->title.' е създадена');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php
/**
 * Created by PhpStorm.
 * User: sylar
 * Date: 26.06.17
 * Time: 00:54
 */

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\RedirectsUsers;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    use RedirectsUsers, ThrottlesLogins;
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */


    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/backend/groups';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function showLoginForm()
    {
        return view('backend.auth.login');
    }

    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function login(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }

    /**
     * Validate the user login request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

    /**
     * Attempt to log the user into the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function attemptLogin(Request $request)
    {
        return $this->guard()->attempt(
            $this->credentials($request), $request->has('remember')
        );
    }

    /**
     * Get the needed authorization credentials from the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    protected function credentials(Request $request)
    {
        return $request->only($this->username(), 'password');
    }

    /**
     * Send the response after the user was authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
            ?: redirect()->intended($this->redirectPath());
    }

    /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        //
    }

    /**
     * Get the failed login response instance.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function sendFailedLoginResponse(Request $request)
    {
        $errors = [$this->username() => trans('auth.failed')];

        if ($request->expectsJson()) {
            return response()->json($errors, 422);
        }

        return redirect()->back()
            ->withInput($request->only($this->username(), 'remember'))
            ->withErrors($errors);
    }

    /**
     * Get the login username to be used by the controller.
     *
     * @return string
     */
    public function username()
    {
        return 'email';
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->flush();

        $request->session()->regenerate();

        return redirect('/');
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }
}

app/Http/Controllers/Backend/ModulesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Assignment;
use App\Models\GroupAge;
use App\Models\Module;
use App\Models\Subject;
use Illuminate\Http\Request;

class ModulesController extends Controller
{
    public function create($subjectId)
    {
        $subject = Subject::findOrFail($subjectId);
        return view('backend.modules.create', [
            'groupAges' => GroupAge::pluck('title', 'id'),
            'subject' => $subject
        ]);
    }

    public function store($subjectId, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'assignment.*.assignment' => 'required',
        ]);

        /** @var Module $module */
        $module = Module::create(['subject_id' => $subjectId, 'title' => $request->get('title')]);

        foreach ($request->assignment as $assignment) {
            Assignment::create(['module_id' => $module->id, 'assignment' => $assignment['assignment'], 'group_age_id' => $assignment['group_age_id']]);
        }

        flash()->success('Успех', 'Модул '.$module->title.' е добавен в системата');
        return redirect()->back();

    }
}

app/Http/Controllers/Backend/ParentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\ChildParent;
use Illuminate\Http\Request;

class ParentsController extends Controller
{
    public function index()
    {
        $parents = ChildParent::with('children')->paginate(5);
        return view('backend.parents.index', ['parents' => $parents]);
    }
}

app/Http/Controllers/Backend/RegisterChildController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Child;
use App\Models\ChildParent;
use App\Models\Group;
use Illuminate\Http\Request;

class RegisterChildController extends Controller
{
    public function create()
    {
        $parents = ChildParent::all();
        $groups = Group::pluck('title', 'id');
        return view('backend.children.register.form', [
            'parents' => $parents,
            'groups' => $groups
        ]);
    }

    public function store(Request $request)
    {

        $this->validate($request, $this->rules($request));
        $child = !is_null($request->parent_id) ? Child::registerWithExistingParent($request) : Child::registerWithNewParent($request);
        flash()->success('Успех', $child->name.' е добавен/а в системата');
        return redirect()->back();

    }

    protected function rules($request)
    {

        $baseRules = [
            'child.name' => 'required',
            'child.egn' => 'required|integer',
            'child.group_id' => 'required',
            'picture' => 'required|image',
        ];

        if (!$request->parent_id) {

            $parentRules = [
                'parent.name' => 'required',
                'parent.email' => 'required|email|unique:parents,email',
                'parent.phone' => 'required',
                'parent.password' => 'required',
                'parent.address' => 'required',
            ];

            $baseRules += $parentRules;
        }

        return $baseRules;
    }
}

app/Http/Controllers/Backend/ScheduleController.php
<?php
/**
 * Created by PhpStorm.
 * User: sylar
 * Date: 25.06.17
 * Time: 23:27
 */

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use App\Models\Group;
use App\Models\Schedule;
use App\Models\Subject;
use Illuminate\Http\Request;

class ScheduleController extends Controller
{
    public function create($groupId)
    {
        $group = Group::findOrFail($groupId);
        $subjects = Subject::all();
        return view('backend.group.schedule.form', [
            'group' => $group,
            'subjects' => $subjects
        ]);
    }

    public function store($id, Request $request)
    {
        $group = Group::findOrFail($id);

        Schedule::where('group_id', $id)->delete();

        foreach($request->get('weekday') as $k => $subjects ) {

            foreach ($subjects as $subject) {
                Schedule::create([
                    'weekday' => $k,
                    'subject_id' => $subject,
                    'group_id' => $id
                ]);
            }

        }

        flash()->success('Успех', 'Програмата на'. $group->title.' е обновена');
        return redirect()->back();

    }

}

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="" />
    <title>@yield('title') | Web Kinderland </title>

    <!-- ========== Css Files ========== -->
    <link href="{{ asset('css/backend/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/backend/plugin/simplemde.css') }}" rel="stylesheet">

    <style>

    </style>

</head>
<body>
<!-- Start Page Loading -->
<div class="loading"><img src="/img/loading.gif" alt="loading-img"></div>

<div id="top" class="clearfix">

    <!-- Start App Logo -->
    <div class="applogo">
        <a href="index.html" class="logo"><img src="/img/logo.jpg" alt=""></a>
    </div>
    <!-- End App Logo -->

    <!-- Start Sidebar Show Hide Button -->
    <a href="#" class="sidebar-open-button"><i class="fa fa-bars"></i></a>
    <a href="#" class="sidebar-open-button-mobile"><i class="fa fa-bars"></i></a>
    <!-- End Sidebar Show Hide Button -->


    <!-- Start Top Right -->
    <ul class="top-right">
        <li class="dropdown link">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle profilebox"><b>{{ Auth::user()->name}}</b><span class="caret"></span></a>
        </li>
    </ul>
    <!-- End Top Right -->
</div>
<!-- END TOP -->

@include('layouts.backend.sidebar')

<div class="content">
    @yield('content')



</div>




<script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>

<!-- ================================================
Bootstrap Core JavaScript File
================================================ -->
<script src="{{ asset('js/bootstrap/bootstrap.min.js') }}"></script>

<!-- ================================================
Plugin.js - Some Specific JS codes for Plugin Settings
================================================ -->

<script type="text/javascript" src="{{ asset('js/sweet-alert/sweet-alert.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/bootstrap-select/bootstrap-select.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/simplemde.js') }}"></script>

@yield('scripts')


@if(session()->has('flash_message'))
    <script>
        swal({
            title: "{!!session('flash_message.title')!!}",
            text: '{!! session('flash_message.message') !!}',
            type: "{{session('flash_message.notice')}}",
            showConfirmButton: "{{session('flash_message.overlay')}}",
            timer: "{{session('flash_message.timer')}}"
        });
    </script>
@endif

</body>

resources/views/layouts/backend/content.blade.php
<div class="content">

    <!-- Start Presentation -->
    <div class="presentation">
        <div class="row titles">
            <div class="col-lg-1 col-md-2">
                <span class="icon title-icon color8-bg"><i class="fa fa-plus"></i></span>
            </div>
            <div class="col-lg-10">
                <h1>Добавяне на потребители</h1>
                <h4>попълнете формата за да добавите ново дете и родител към вашето учебно заведение</h4>
            </div>
        </div>

    </div>
    <!-- End Presentation -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START CONTAINER -->
    <div class="container-default">
        <div class="row">
            <div class="col-md-12 padding-0">
                <div class="panel panel-transparent">

                    <div class="panel-body">
                        <div role="tabpanel">

                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs nav-justified" role="tablist">
                                <li role="presentation" class="active"><a href="#child" aria-controls="child" role="tab" data-toggle="tab">Регистрация на дете</a></li>
                                <li role="presentation"><a href="#parent" aria-controls="parent" role="tab" data-toggle="tab">Регистрация на родител</a></li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active padding-b-50" id="child">
                                    <form class="form-horizontal">
                                        <div class="row">
                                            <div class="col-sm-10 col-sm-push-2 margin-b-35">
                                                <h2 class="margin-b-0">Регистрация на дете</h2>
                                                <h5 class="margin-t-0">попълнете необходимата информация за да добавите ново дете към системата на учебното заведение</h5>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2"></label>
                                            <div class="col-sm-10 profile-center">
                                                <img src="/img/image_preview.png" alt="img" class="profile-img">
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            <label class="col-sm-2"></label>
                                            <div class="col-sm-10 profile-center">
                                                <a href="#" class="btn btn-default"><i class="fa fa-picture-o"></i>Качи снимка</a>
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            <label for="input002" class="col-sm-2 control-label form-label">Имена</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="input002">
                                            </div>
                                        </div>

                                        <div class="form-group required">
                                            <label for="input002" class="col-sm-2 control-label form-label">ЕГН</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="input002">
                                            </div>
                                        </div>

                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label form-label">Група</label>
                                            <div class="col-sm-10">
                                                <select class="col-md-12 selectpicker selectpicker required" required>
                                                    <option>1-а група "Калинка"</option>
                                                    <option>1-б група "Калинка"</option>
                                                    <option>2-а група "Калинка"</option>
                                                </select>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                                <div role="tabpanel" class="tab-pane" id="parent">
                                    <form class="form-horizontal">
                                        <div class="row">
                                            <div class="col-sm-10 col-sm-push-2">
                                                <h2 class="margin-b-0">Родителят има регистрация?</h2>
                                                <h5 class="margin-t-0">ако родителят вече има регистрация в системата, моля изберете името му от списъка</h5>
                                            </div>
                                            <div class="form-group col-lg-12">
                                                <label class="col-sm-2 control-label form-label"></label>
                                                <div class="col-sm-10">
                                                    <select class="col-md-12 selectpicker selectpicker required" required>
                                                        <option>Иван Иванов</option>
                                                        <option>Иван Иванов</option>
                                                        <option>Иван Иванов</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-10 col-sm-push-2 margin-b-35">
                                                <h2 class="margin-b-0">Регистрация на родител</h2>
                                                <h5 class="margin-t-0">попълнете необходимата информация за да добавите нов родител към системата на учебното заведение</h5>
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            <label for="input002" class="col-sm-2 control-label form-label">Имена</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="input002">
                                            </div>
                                        </div>

                                        <div class="form-group required">
                                            <label for="input002" class="col-sm-2 control-label form-label">Телефон</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="input002">
                                            </div>
                                        </div>

                                        <div class="form-group required">
                                            <label for="input002" class="col-sm-2 control-label form-label">Email</label>
                                            <div class="col-sm-10">
                                                <input type="email" class="form-control" id="input002">
                                            </div>
                                        </div>

                                        <div class="form-group required">
                                            <label for="input002" class="col-sm-2 control-label form-label">Парола</label>
                                            <div class="col-sm-10">
                                                <input type="password" value="231231231" readonly class="form-control" id="input002">
                                            </div>
                                        </div>

                                        <div class="form-group required">
                                            <label class="col-sm-2 control-label form-label">Адрес</label>
                                            <div class="col-sm-10">
                                                <textarea class="form-control" rows="3" id="textarea1" ></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label form-label"></label>
                                            <div class="col-sm-10">
                                                <button  type="submit" class="btn btn-default pull-right">Запази</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <!-- END CONTAINER -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->


    <!-- Start Footer -->
    <div class="row footer">

    </div>
    <!-- End Footer -->


</div>
<!-- End Content -->

resources/views/layouts/backend/sidebar.blade.php
<!-- START SIDEBAR -->
<div class="sidebar clearfix">

    <ul class="sidebar-panel nav">
        <li><a href="index.html"><span class="icon color5"><i class="fa fa-home"></i></span>Начало</a></li>
        <li><a href="kinder_news.html"><span class="icon color6"><i class="fa fa-newspaper-o"></i></span>Новини</a></li>
        <li><a href="{{route('register-child.create')}}" class="{{menuActiveRoute('register-child.create')}}"><span class="icon color6"><i class="fa fa-plus"></i></span>Регистрация</a></li>
        <li><a href="kinder_menu.html"><span class="icon color6"><i class="fa fa-cutlery"></i></span>Меню</a></li>
        <li><a href="kinder_events.html"><span class="icon color6"><i class="fa fa-calendar-o"></i></span>Събития</a></li>
        <li><a href="#" class="{{menuActiveRoute('group.schedule.create')}} {{menuActiveRoute('group-age')}} {{menuActiveRoute('groups')}}" ><span class="icon color7 "><i class="fa fa-users"></i></span>Групи<span class="caret"></span></a>
            <ul>
                <li><a href="{{route('group-age.index')}}">Възрастови групи</a></li>
                <li><a href="{{route('groups.index')}}">Детски групи</a></li>
            </ul>
        </li>
        <li><a class=" {{menuActiveRoute('parents')}}" href="{{route('parents.index')}}"><span class="icon color8"><i class="fa fa-female"></i></span>Родители</a></li>
        <li><a class="{{menuActiveRoute('teachers')}}" href="{{route('teachers.index')}}"><span class="icon color8"><i class="fa fa-graduation-cap"></i></span>Учители</a></li>
        <li><a class="{{menuActiveRoute('subjects')}}" href="{{route('subjects.index')}}"><span class="icon color8"><i class="fa fa-book"></i></span>Учебен план</a></li>
    </ul>

    <ul class="sidebar-panel nav">
        <li><a href="#"><span class="icon color8"><i class="fa fa-user"></i></span>Профил</a></li>
        <li><a href="#"><span class="icon color8"><i class="fa fa-sign-out"></i></span>Изход</a></li>
    </ul>
</div>