routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/news', 'NewsController@index')->name('news');
Route::get('/team', 'TeamController@index')->name('team');
Route::get('/schedule', 'ScheduleController@index')->name('schedule');
Route::get('/groups', 'GroupsController@index')->name('groups');



//Route::namespace('Backend')->prefix('backend')->group(function () {
Route::group(['namespace' => 'Backend', 'prefix' => 'backend'], function () {

    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');

    Route::group(['middleware' => 'auth' ], function() {


        Route::resource('group-age', 'GroupAgeController');
        Route::resource('groups', 'GroupsController');

        Route::get('/schedule/{id}', ['as' => 'group.schedule.create', 'uses' => 'ScheduleController@create']);
        Route::post('/schedule/{id}', ['as' => 'group.schedule.store', 'uses' => 'ScheduleController@store']);

        Route::resource('teachers', 'TeachersController');
        Route::resource('subjects', 'SubjectsController');
        Route::resource('subjects.modules', 'ModulesController');

        Route::get('register-child', ['as' => 'register-child.create', 'uses' => 'RegisterChildController@create']);
        Route::post('register-child', ['as' => 'register-child.store', 'uses' => 'RegisterChildController@store']);
        Route::resource('parents', 'ParentsController');
    });

});

app/Models/GroupAge.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GroupAge extends Model
{
    protected $guarded = [];


    public function groups()
    {
        return $this->hasMany(Group::class);
    }
}

app/Http/Controllers/Backend/GroupAgeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\GroupAge;
use Illuminate\Http\Request;

class GroupAgeController extends Controller
{
    public function index()
    {
        $groupAges = GroupAge::all();
        return view('backend.group-age.index', ['groupAge' => new GroupAge, 'groupAges' => $groupAges ]);

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'from'  => 'required|integer',
            'to'  => 'required|integer',
        ]);

        $groupAge = GroupAge::create($request->only(['title', 'from', 'to']));
        flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е създадена');
        return redirect()->back();
    }

    public function edit($id)
    {
        $groupAge = GroupAge::findOrFail($id);
        return view('backend.group-age.edit', ['groupAge' => $groupAge]);
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'from'  => 'required|integer',
            'to'  => 'required|integer',
        ]);

        /** @var GroupAge $groupAge */
        $groupAge = GroupAge::findOrFail($id);
        $groupAge->update($request->only(['title', 'from', 'to']));

        flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е редактирана');
        return redirect()->route('group-age.index');

    }

    public function destroy($id)
    {
        /** @var GroupAge $groupAge */
        $groupAge = GroupAge::withCount('groups')->findOrFail($id);

        if ($groupAge->groups_count != 0) {
            flash()->error('Възникна грешка', 'Възрастовата група '.$groupAge->title.' не може да бъде изтрита');
        } else {
            $groupAge->delete();
            flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е изтрита');
        }

        return redirect()->route('group-age.index');
    }
}

app/Http/Controllers/Backend/GroupsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Group;
use App\Models\GroupAge;
use App\Models\Teacher;
use Illuminate\Http\Request;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $groups = Group::with('groupAge', 'teachers')->get();
        return view('backend.group.index', [
                'groupAges' => GroupAge::pluck('title', 'id'),
                'group' => new Group,
                'groups' => $groups,
                'teachers' => Teacher::pluck('name', 'id')
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'teachers' => 'required',
            'group_age_id' => 'exists:group_ages,id'
        ]);


        /** @var Group $group */
        $group = Group::create($request->only(['title', 'group_age_id', 'description']));

        $group->teachers()->sync($request->get('teachers'));

        flash()->success('Успех', 'Детска група '.$group->title.' е създадена');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php
/**
 * Created by PhpStorm.
 * User: sylar
 * Date: 26.06.17
 * Time: 00:54
 */

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\RedirectsUsers;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    use RedirectsUsers, ThrottlesLogins;
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */


    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/backend/groups';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function showLoginForm()
    {
        return view('backend.auth.login');
    }

    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function login(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }

    /**
     * Validate the user login request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

    /**
     * Attempt to log the user into the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function attemptLogin(Request $request)
    {
        return $this->guard()->attempt(
            $this->credentials($request), $request->has('remember')
        );
    }

    /**
     * Get the needed authorization credentials from the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    protected function credentials(Request $request)
    {
        return $request->only($this->username(), 'password');
    }

    /**
     * Send the response after the user was authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
            ?: redirect()->intended($this->redirectPath());
    }

    /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        //
    }

    /**
     * Get the failed login response instance.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function sendFailedLoginResponse(Request $request)
    {
        $errors = [$this->username() => trans('auth.failed')];

        if ($request->expectsJson()) {
            return response()->json($errors, 422);
        }

        return redirect()->back()
            ->withInput($request->only($this->username(), 'remember'))
            ->withErrors($errors);
    }

    /**
     * Get the login username to be used by the controller.
     *
     * @return string
     */
    public function username()
    {
        return 'email';
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->flush();

        $request->session()->regenerate();

        return redirect('/');
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }
}

app/Http/Controllers/Backend/ModulesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Assignment;
use App\Models\GroupAge;
use App\Models\Module;
use App\Models\Subject;
use Illuminate\Http\Request;

class ModulesController extends Controller
{
    public function create($subjectId)
    {
        $subject = Subject::findOrFail($subjectId);
        return view('backend.modules.create', [
            'groupAges' => GroupAge::pluck('title', 'id'),
            'subject' => $subject
        ]);
    }

    public function store($subjectId, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'assignment.*.assignment' => 'required',
        ]);

        /** @var Module $module */
        $module = Module::create(['subject_id' => $subjectId, 'title' => $request->get('title')]);

        foreach ($request->assignment as $assignment) {
            Assignment::create(['module_id' => $module->id, 'assignment' => $assignment['assignment'], 'group_age_id' => $assignment['group_age_id']]);
        }

        flash()->success('Успех', 'Модул '.$module->title.' е добавен в системата');
        return redirect()->back();

    }
}

app/Http/Controllers/Backend/ParentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\ChildParent;
use Illuminate\Http\Request;

class ParentsController extends Controller
{
    public function index()
    {
        $parents = ChildParent::with('children')->paginate(5);
        return view('backend.parents.index', ['parents' => $parents]);
    }
}

app/Http/Controllers/Backend/RegisterChildController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Child;
use App\Models\ChildParent;
use App\Models\Group;
use Illuminate\Http\Request;

class RegisterChildController extends Controller
{
    public function create()
    {
        $parents = ChildParent::all();
        $groups = Group::pluck('title', 'id');
        return view('backend.children.register.form', [
            'parents' => $parents,
            'groups' => $groups
        ]);
    }

    public function store(Request $request)
    {

        $this->validate($request, $this->rules($request));
        $child = !is_null($request->parent_id) ? Child::registerWithExistingParent($request) : Child::registerWithNewParent($request);
        flash()->success('Успех', $child->name.' е добавен/а в системата');
        return redirect()->back();

    }

    protected function rules($request)
    {

        $baseRules = [
            'child.name' => 'required',
            'child.egn' => 'required|integer',
            'child.group_id' => 'required',
            'picture' => 'required|image',
        ];

        if (!$request->parent_id) {

            $parentRules = [
                'parent.name' => 'required',
                'parent.email' => 'required|email|unique:parents,email',
                'parent.phone' => 'required',
                'parent.password' => 'required',
                'parent.address' => 'required',
            ];

            $baseRules += $parentRules;
        }

        return $baseRules;
    }
}

app/Http/Controllers/Backend/ScheduleController.php
<?php
/**
 * Created by PhpStorm.
 * User: sylar
 * Date: 25.06.17
 * Time: 23:27
 */

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use App\Models\Group;
use App\Models\Schedule;
use App\Models\Subject;
use Illuminate\Http\Request;

class ScheduleController extends Controller
{
    public function create($groupId)
    {
        $group = Group::findOrFail($groupId);
        $subjects = Subject::all();
        return view('backend.group.schedule.form', [
            'group' => $group,
            'subjects' => $subjects
        ]);
    }

    public function store($id, Request $request)
    {
        $group = Group::findOrFail($id);

        Schedule::where('group_id', $id)->delete();

        foreach($request->get('weekday') as $k => $subjects ) {

            foreach ($subjects as $subject) {
                Schedule::create([
                    'weekday' => $k,
                    'subject_id' => $subject,
                    'group_id' => $id
                ]);
            }

        }

        flash()->success('Успех', 'Програмата на'. $group->title.' е обновена');
        return redirect()->back();

    }

}

resources/views/backend/group-age/edit.blade.php
@extends('layouts.backend.app')
@section('title', 'Редактиране на '.$groupAge->title)
@section('content')
    <div class="presentation">
        <div class="row titles">
            <div class="col-lg-1 col-md-2">
                <span class="icon title-icon color8-bg"><i class="fa fa-child"></i></span>
            </div>
            <div class="col-lg-10">
                <h1>Редакция на възрастова група {{$groupAge->title}} </h1>
            </div>
        </div>
    </div>

    <div class="container-default">
        <div class="row">
            <div class="col-lg-12">
                    @include('backend.group-age.form')
            </div>
        </div>
    </div>

@endsection

resources/views/backend/group-age/form.blade.php
<form class="form-horizontal" method="post" action="{{ $groupAge->exists ? route('group-age.update', $groupAge->id) : route('group-age.store')}}" >
    {{csrf_field()}}

    @if($groupAge->exists)
        {{method_field('put')}}
    @endif

    <div class="titles">


        <h2>{{$groupAge->exists ? '' : 'Добави възрастова група' }} </h2>
    </div>
    <div class="form-group {{$errors->has('title') ? 'has-error'  : '' }}">
        <label  class="col-sm-2 control-label form-label">Име</label>
        <div class="col-sm-10">
            <input type="text" name="title" class="form-control" value="{{ old('title', $groupAge->title) }}" >
            @if ($errors->has('title'))
                <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span>
            @endif
        </div>
    </div>

    <div class="form-group {{$errors->has('from') ? 'has-error'  : '' }} ">
        <label for="input002" class="col-sm-2 control-label form-label">Години от</label>
        <div class="col-sm-10">
            <input type="text" name="from" class="form-control" value="{{ old('from', $groupAge->from) }}" >
            @if ($errors->has('from'))
                <span class="help-block">
                            <strong>{{ $errors->first('from') }}</strong>
                        </span>
            @endif
        </div>
    </div>

    <div class="form-group {{$errors->has('to') ? 'has-error'  : '' }}">
        <label class="col-sm-2 control-label form-label">Години до</label>
        <div class="col-sm-10">
            <input type="text" name="to" value="{{ old('to', $groupAge->to) }}" class="form-control" id="input002">
            @if ($errors->has('to'))
                <span class="help-block">
                            <strong>{{ $errors->first('to') }}</strong>
                        </span>
            @endif
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label form-label"></label>
        <div class="col-sm-10">
            <button type="submit" class="btn btn-default pull-right">Запази</button>
        </div>
    </div>
</form>

resources/views/backend/group-age/index.blade.php
@extends('layouts.backend.app')
@section('title', 'Възрастови групи')
@section('content')
    <div class="presentation">
        <div class="row titles">
            <div class="col-lg-1 col-md-2">
                <span class="icon title-icon color8-bg"><i class="fa fa-child"></i></span>
            </div>
            <div class="col-lg-10">
                <h1>Добавяне на възрастова група</h1>
                <h4>попълнете формата за да добавите нова възрастова групата</h4>
            </div>
        </div>
    </div>

    <div class="container-default">
        <div class="row">
            <div class="col-lg-4">
                @include('backend.group-age.form')
            </div>

            <div class="col-lg-8">
                <div class="titles">
                    <h2>Списък с възрастови групи</h2>
                </div>

                <div class="panel panel-default">

                    <div class="panel-body table-responsive">

                        <div id="example0_wrapper" class="dataTables_wrapper"><div class="dataTables_length" id="example0_length">

                            </div>

                            <table id="example0" class="table display dataTable" role="grid" aria-describedby="example0_info">
                                <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 253px;">Име</th>

                                    <th class="sorting" tabindex="0" aria-controls="example0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 400px;">Години от</th>
                                    <th class="sorting" tabindex="0" aria-controls="example0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 186px;">Години до</th>
                                    <th class="sorting" tabindex="0" aria-controls="example0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 186px;">Действия</th>
                                </tr>
                                </thead>



                                <tbody>

                                @foreach($groupAges as $k => $groupAge)
                                    <tr role="row" class="{{ $k %2 == 0 ? 'odd' : 'event' }}">
                                        <td>{{$groupAge->title}}</td>
                                        <td>{{$groupAge->from}}</td>
                                        <td>{{$groupAge->to}}</td>
                                        <td>
                                            <div class="btn-group" role="group" aria-label="...">
                                                <a href="{{route('group-age.edit', $groupAge->id)}}"  class="btn btn-default"><i class="fa fa-pencil"></i></a>
                                                <form action="{{ route('group-age.destroy', $groupAge->id) }}" method="POST" style="display: inline-block; ">
                                                    {{ csrf_field() }}
                                                    {{method_field('delete')}}
                                                    <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


@endsection