routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/news', 'NewsController@index')->name('news');
Route::get('/team', 'TeamController@index')->name('team');
Route::get('/schedule', 'ScheduleController@index')->name('schedule');
Route::get('/groups', 'GroupsController@index')->name('groups');



//Route::namespace('Backend')->prefix('backend')->group(function () {
Route::group(['namespace' => 'Backend', 'prefix' => 'backend'], function () {

    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');

    Route::group(['middleware' => 'auth' ], function() {


        Route::resource('group-age', 'GroupAgeController');
        Route::resource('groups', 'GroupsController');

        Route::get('/schedule/{id}', ['as' => 'group.schedule.create', 'uses' => 'ScheduleController@create']);
        Route::post('/schedule/{id}', ['as' => 'group.schedule.store', 'uses' => 'ScheduleController@store']);

        Route::resource('teachers', 'TeachersController');
        Route::resource('subjects', 'SubjectsController');
        Route::resource('subjects.modules', 'ModulesController');

        Route::get('register-child', ['as' => 'register-child.create', 'uses' => 'RegisterChildController@create']);
        Route::post('register-child', ['as' => 'register-child.store', 'uses' => 'RegisterChildController@store']);
        Route::resource('parents', 'ParentsController');
    });

});

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $guarded = [];

    public function type()
    {
        return $this->belongsTo(TeacherType::class, 'teacher_type_id');
    }

    public function groups()
    {
        return $this->hasMany(Group::class);
    }
}

app/Models/TeacherType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TeacherType extends Model
{
    //
}

app/Http/Controllers/Backend/GroupAgeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\GroupAge;
use Illuminate\Http\Request;

class GroupAgeController extends Controller
{
    public function index()
    {
        $groupAges = GroupAge::all();
        return view('backend.group-age.index', ['groupAge' => new GroupAge, 'groupAges' => $groupAges ]);

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'from'  => 'required|integer',
            'to'  => 'required|integer',
        ]);

        $groupAge = GroupAge::create($request->only(['title', 'from', 'to']));
        flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е създадена');
        return redirect()->back();
    }

    public function edit($id)
    {
        $groupAge = GroupAge::findOrFail($id);
        return view('backend.group-age.edit', ['groupAge' => $groupAge]);
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'from'  => 'required|integer',
            'to'  => 'required|integer',
        ]);

        /** @var GroupAge $groupAge */
        $groupAge = GroupAge::findOrFail($id);
        $groupAge->update($request->only(['title', 'from', 'to']));

        flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е редактирана');
        return redirect()->route('group-age.index');

    }

    public function destroy($id)
    {
        /** @var GroupAge $groupAge */
        $groupAge = GroupAge::withCount('groups')->findOrFail($id);

        if ($groupAge->groups_count != 0) {
            flash()->error('Възникна грешка', 'Възрастовата група '.$groupAge->title.' не може да бъде изтрита');
        } else {
            $groupAge->delete();
            flash()->success('Успех', 'Възрастова група '.$groupAge->title.' е изтрита');
        }

        return redirect()->route('group-age.index');
    }
}

app/Http/Controllers/Backend/GroupsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Group;
use App\Models\GroupAge;
use App\Models\Teacher;
use Illuminate\Http\Request;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $groups = Group::with('groupAge', 'teachers')->get();
        return view('backend.group.index', [
                'groupAges' => GroupAge::pluck('title', 'id'),
                'group' => new Group,
                'groups' => $groups,
                'teachers' => Teacher::pluck('name', 'id')
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'teachers' => 'required',
            'group_age_id' => 'exists:group_ages,id'
        ]);


        /** @var Group $group */
        $group = Group::create($request->only(['title', 'group_age_id', 'description']));

        $group->teachers()->sync($request->get('teachers'));

        flash()->success('Успех', 'Детска група '.$group->title.' е създадена');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php
/**
 * Created by PhpStorm.
 * User: sylar
 * Date: 26.06.17
 * Time: 00:54
 */

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\RedirectsUsers;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    use RedirectsUsers, ThrottlesLogins;
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */


    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/backend/groups';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function showLoginForm()
    {
        return view('backend.auth.login');
    }

    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function login(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }

    /**
     * Validate the user login request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

    /**
     * Attempt to log the user into the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function attemptLogin(Request $request)
    {
        return $this->guard()->attempt(
            $this->credentials($request), $request->has('remember')
        );
    }

    /**
     * Get the needed authorization credentials from the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    protected function credentials(Request $request)
    {
        return $request->only($this->username(), 'password');
    }

    /**
     * Send the response after the user was authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
            ?: redirect()->intended($this->redirectPath());
    }

    /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        //
    }

    /**
     * Get the failed login response instance.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function sendFailedLoginResponse(Request $request)
    {
        $errors = [$this->username() => trans('auth.failed')];

        if ($request->expectsJson()) {
            return response()->json($errors, 422);
        }

        return redirect()->back()
            ->withInput($request->only($this->username(), 'remember'))
            ->withErrors($errors);
    }

    /**
     * Get the login username to be used by the controller.
     *
     * @return string
     */
    public function username()
    {
        return 'email';
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->flush();

        $request->session()->regenerate();

        return redirect('/');
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }
}

app/Http/Controllers/Backend/ModulesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Assignment;
use App\Models\GroupAge;
use App\Models\Module;
use App\Models\Subject;
use Illuminate\Http\Request;

class ModulesController extends Controller
{
    public function create($subjectId)
    {
        $subject = Subject::findOrFail($subjectId);
        return view('backend.modules.create', [
            'groupAges' => GroupAge::pluck('title', 'id'),
            'subject' => $subject
        ]);
    }

    public function store($subjectId, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'assignment.*.assignment' => 'required',
        ]);

        /** @var Module $module */
        $module = Module::create(['subject_id' => $subjectId, 'title' => $request->get('title')]);

        foreach ($request->assignment as $assignment) {
            Assignment::create(['module_id' => $module->id, 'assignment' => $assignment['assignment'], 'group_age_id' => $assignment['group_age_id']]);
        }

        flash()->success('Успех', 'Модул '.$module->title.' е добавен в системата');
        return redirect()->back();

    }
}

app/Http/Controllers/Backend/ParentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\ChildParent;
use Illuminate\Http\Request;

class ParentsController extends Controller
{
    public function index()
    {
        $parents = ChildParent::with('children')->paginate(5);
        return view('backend.parents.index', ['parents' => $parents]);
    }
}

app/Http/Controllers/Backend/RegisterChildController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Child;
use App\Models\ChildParent;
use App\Models\Group;
use Illuminate\Http\Request;

class RegisterChildController extends Controller
{
    public function create()
    {
        $parents = ChildParent::all();
        $groups = Group::pluck('title', 'id');
        return view('backend.children.register.form', [
            'parents' => $parents,
            'groups' => $groups
        ]);
    }

    public function store(Request $request)
    {

        $this->validate($request, $this->rules($request));
        $child = !is_null($request->parent_id) ? Child::registerWithExistingParent($request) : Child::registerWithNewParent($request);
        flash()->success('Успех', $child->name.' е добавен/а в системата');
        return redirect()->back();

    }

    protected function rules($request)
    {

        $baseRules = [
            'child.name' => 'required',
            'child.egn' => 'required|integer',
            'child.group_id' => 'required',
            'picture' => 'required|image',
        ];

        if (!$request->parent_id) {

            $parentRules = [
                'parent.name' => 'required',
                'parent.email' => 'required|email|unique:parents,email',
                'parent.phone' => 'required',
                'parent.password' => 'required',
                'parent.address' => 'required',
            ];

            $baseRules += $parentRules;
        }

        return $baseRules;
    }
}

app/Http/Controllers/Backend/ScheduleController.php
<?php
/**
 * Created by PhpStorm.
 * User: sylar
 * Date: 25.06.17
 * Time: 23:27
 */

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use App\Models\Group;
use App\Models\Schedule;
use App\Models\Subject;
use Illuminate\Http\Request;

class ScheduleController extends Controller
{
    public function create($groupId)
    {
        $group = Group::findOrFail($groupId);
        $subjects = Subject::all();
        return view('backend.group.schedule.form', [
            'group' => $group,
            'subjects' => $subjects
        ]);
    }

    public function store($id, Request $request)
    {
        $group = Group::findOrFail($id);

        Schedule::where('group_id', $id)->delete();

        foreach($request->get('weekday') as $k => $subjects ) {

            foreach ($subjects as $subject) {
                Schedule::create([
                    'weekday' => $k,
                    'subject_id' => $subject,
                    'group_id' => $id
                ]);
            }

        }

        flash()->success('Успех', 'Програмата на'. $group->title.' е обновена');
        return redirect()->back();

    }

}

resources/views/backend/teachers/create.blade.php
@extends('layouts.backend.app')
@section('title', 'Създаване на учителски профил')
@section('content')
    <div class="row presentation">
        <div class="col-lg-8 col-md-6 titles">
            <h1>Добавяне на учител</h1>
            <h4>попълнете формата за да добавите нов учител към вашето учебно заведение</h4>
        </div>
    </div>

    <div class="container-default">
        <form class="form-horizontal" method="post" action="{{route('teachers.store')}}" enctype="multipart/form-data" >
            {{csrf_field()}}
            <div class="form-group">
                <label class="col-sm-2"></label>
                <div class="col-sm-10 profile-center">

                    <div class = "prd-img-prv">
                        <img src="/img/image_preview.png" alt="img" class="profile-img">
                    </div>

                </div>
            </div>
            <div class="form-group {{$errors->has('picture') ? 'has-error'  : '' }}">
                <label class="col-sm-2"></label>
                <div class="col-sm-10 profile-center">
                    <button onclick="chooseFile()"; type="button" class="btn btn-default"><i class="fa fa-picture-o"></i>Качи снимка</button>
                    <input type="file"  name="picture"  class="hidden" id="fileInput"   data-previewable="true" data-preview-container=".prd-img-prv" />

                    @if ($errors->has('picture'))
                        <span class="help-block">
                            <strong>{{ $errors->first('picture') }}</strong>
                        </span>
                    @endif


                </div>
            </div>

            <div class="form-group {{$errors->has('name') ? 'has-error'  : '' }}">
                <label for="input002" class="col-sm-2 control-label form-label">Имена</label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control"  value="{{ old('name') }}">
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group {{$errors->has('email') ? 'has-error'  : '' }} ">
                <label for="input002" class="col-sm-2 control-label form-label">Емайл</label>
                <div class="col-sm-10">
                    <input type="email" name="email" class="form-control" value="{{ old('email') }}">
                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group {{$errors->has('phone') ? 'has-error'  : '' }} ">
                <label for="input002" class="col-sm-2 control-label form-label">Телефон</label>
                <div class="col-sm-10">
                    <input type="text" name="phone" class="form-control" value="{{ old('phone') }}">
                    @if ($errors->has('phone'))
                        <span class="help-block">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group {{$errors->has('bio') ? 'has-error'  : '' }}">
                <label class="col-sm-2 control-label form-label">Биография</label>
                <div class="col-sm-10">
                    <textarea id="bio" name="bio">{{ old('bio') }}</textarea>

                    @if ($errors->has('bio'))
                        <span class="help-block">
                            <strong>{{ $errors->first('bio') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label form-label">Длъжност</label>
                <div class="col-sm-10">
                    <select name="teacher_type_id" class="selectpicker selectpicker" style="width: 100%">
                        @foreach($teacherTypes as $id => $title)
                            <option {{old('teacher_type_id') == $id ? 'selected="selected"' : '' }} value="{{$id}}">{{$title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>


            <div class="form-group">
                <label class="col-sm-2 control-label form-label"></label>
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-default pull-right">Запази</button>
                </div>
            </div>


        </form>

    </div>


@endsection

@section('scripts')
    <script>
        var simplemde = new SimpleMDE({ element: document.getElementById("bio") });
        function chooseFile(e) {

            $("#fileInput").click();
        }

        function assignFilePreviews() {
            $( 'input[data-previewable=\"true\"]' ).change(function() {
                var prvCnt = $(this).attr('data-preview-container');
                if(prvCnt) {
                    if (this.files && this.files[0]) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            var img = $('<img>', {width: '184px', height:'227px'});
                            img.attr('src', e.target.result);
                            img.error(function() {
                                $(prvCnt).html('');
                            });
                            $(prvCnt).html('');
                            img.appendTo(prvCnt);
                        }
                        reader.readAsDataURL(this.files[0]);
                    }
                }
            });
        }
        $(document).ready(function() {
            assignFilePreviews();


        });

    </script>
@endsection

resources/views/backend/teachers/index.blade.php
@extends('layouts.backend.app')
@section('title', 'Учители')
@section('content')
    <div class="presentation">
        <div class="row titles">
            <div class="col-lg-1 col-md-2">
                <span class="icon title-icon color8-bg"><i class="fa fa-graduation-cap"></i></span>
            </div>
            <div class="col-lg-10">
                <h1>Учители</h1>
                <h4>регистрирани в системата учители</h4>
            </div>
        </div>
    </div>


    <div class="container-padding">
        <div class="row">
            <div class="col-md-12">

                <div class="pull-right">
                    <a class="btn btn-default" href="{{route('teachers.create')}}">
                        <i class="fa fa-plus"></i> Нов учител
                    </a>
                </div>


                <div class="clearfix"></div>
                <br>

                <div class="panel panel-default">
                    <div class="panel-body table-responsive">

                        <div id="example0_wrapper" class="dataTables_wrapper">
                            <div class="dataTables_length" id="example0_length"></div>

                            <table id="example0" class="table display dataTable" role="grid" aria-describedby="example0_info">

                                <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 253px;">Име</th>
                                    <th>Длъжност</th>
                                    <th>Телефон</th>
                                    <th>Емайл</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($teachers as $index => $teacher)
                                    <tr role="row" class="{{$index % 2 != 0 ? 'odd' : 'even' }}">
                                        <td>{{$teacher->name}}</td>
                                        <td>{{$teacher->type->title}}</td>
                                        <td>{{$teacher->phone}}</td>
                                        <td>{{$teacher->email}}</td>
                                        <td >
                                            <div class="btn-group" role="group" aria-label="...">
                                                <a  href="{{route('teachers.edit', $teacher->id)}}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>

                                                <form action="{{ route('teachers.destroy', $teacher->id) }}" method="POST" style="display: inline-block; ">
                                                    {{ csrf_field() }}
                                                    {{method_field('delete')}}
                                                    <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                                                </form>

                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        <div class="pull-right">
                            {{$teachers->links()}}
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection